#include "/libs/settings.glsl"

#ifdef WORLD

vec3 ambientDayColor = vec3(AMBIENT_DAY_COLOR_R,AMBIENT_DAY_COLOR_G,AMBIENT_DAY_COLOR_B);
vec3 ambientTwilightColor = vec3(AMBIENT_TWILIGHT_COLOR_R,AMBIENT_TWILIGHT_COLOR_G,AMBIENT_TWILIGHT_COLOR_B);
vec3 ambientNightColor = vec3(AMBIENT_NIGHT_COLOR_R,AMBIENT_NIGHT_COLOR_G,AMBIENT_NIGHT_COLOR_B);

#elif END

vec3 ambientDayColor = vec3(AMBIENT_END_COLOR_R,AMBIENT_END_COLOR_G,AMBIENT_END_COLOR_B);
vec3 ambientTwilightColor = vec3(AMBIENT_END_COLOR_R,AMBIENT_END_COLOR_G,AMBIENT_END_COLOR_B);
vec3 ambientNightColor = vec3(AMBIENT_END_COLOR_R,AMBIENT_END_COLOR_G,AMBIENT_END_COLOR_B);

#elif NETHER 

vec3 ambientDayColor = vec3(AMBIENT_NETHER_COLOR_R,AMBIENT_NETHER_COLOR_G,AMBIENT_NETHER_COLOR_B);
vec3 ambientTwilightColor = vec3(AMBIENT_NETHER_COLOR_R,AMBIENT_NETHER_COLOR_G,AMBIENT_NETHER_COLOR_B);
vec3 ambientNightColor = vec3(AMBIENT_NETHER_COLOR_R,AMBIENT_NETHER_COLOR_G,AMBIENT_NETHER_COLOR_B);

#endif